services:
  - type: web
    name: aqsha-project
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: aqsha-data
      mountPath: /opt/render/project/src/persistent
      sizeGB: 1
